import React from 'react';

import Page from '../../components/Page';

const PrivacyPage = () => (
  <Page>
    <h1>Terms & Conditions</h1>
    <p>These Terms of Service ("Agreement") are between you, together with any entity you are representing (collectively, "You"), and Vidhub ("Vidhub," "Edusync," “We,” “Us,” or “Our”). By registering with Vidhub, using Our website at vidhub.co, edusync.co or any mobile version of Our website (together, "Site"), or using any services provided through Our Site (“Services”), (1) You agree to be bound by this Agreement, including the additional terms referenced in Section 1 below (“Additional Terms”) and (2) You represent that You are eighteen (18) years of age or older and, if You are representing an entity, You have all required authority and power to bind the entity to this Agreement. IF YOU DO NOT AGREE TO BE BOUND BY THIS AGREEMENT, OR ANY OF THE ADDITIONAL TERMS THAT APPLY TO YOU, OR IF YOU DO NOT HAVE SUCH AUTHORITY, YOU RE NOT AUTHORIZED TO ACCESS OR USE OUR SITE OR SERVICES.</p>
    <h3>1. Additional Terms</h3>
    <p>(a) Please review the Vidhub Privacy Policy ("Privacy Policy") The provisions of the Privacy Policy apply to You and are incorporated into, and considered a part of, this Agreement. (b) Please review Our other policies referenced in this Agreement and hyperlinked herein below. The provisions of such policies may apply to You and are incorporated into, and considered a part of, this Agreement.</p>
    <h3>2. Vidhub Site; Site Content.</h3>
    <p>The Vidhub Site is a copyrighted work belonging to Vidhub. We or Our suppliers exclusively own the information and content made available on or through the Site (other than information or content You provide) and the information and content in any communications Vidhub sends You (collectively, "Site Content"). You may use the Site and Site Content only in accordance with this Agreement. Subject to the terms and conditions of this Agreement (including Your compliance with this Agreement), Vidhub grants You a limited, non-exclusive, non-transferable, non-sublicenseable, revocable license to view and use the Vidhub Site Content (other than Software (defined in Section 3 below) which is licensed only under the terms of Section 3 below) for Your personal or internal business purposes. You may not use the Vidhub Site Content except as expressly authorized under this Agreement. You agree that any copy of the Vidhub Site Content that You make shall retain all copyright and other proprietary notices in the same form and manner as on the original. Except as expressly authorized under this Agreement or to the extent otherwise permitted under applicable law, You may not use, download, upload, print, display, perform, reproduce, publish, license, post, transmit, modify, create derivative works of, reverse engineer, disassemble, decompile, adapt, distribute, transfer, or exploit any Vidhub Site Content in whole or in part without Our prior written authorization.</p>
    <h3>3. Your Account</h3>
    <p>To access or use Our Services, You will be required to register and obtain an account on the Site. You will receive (or choose) a password upon completing the registration process. You are responsible for maintaining the confidentiality of Your password, and all activities that occur under Your account. You agree to (1) immediately notify Us of any unauthorized use of Your account or any other breach of security and (2) ensure that You fully exit from Your account at the end of each session. We will not be liable (to You or any third party) for any loss or damage arising from or related to the unauthorized use of Your account (unless such use is directly caused by Our gross negligence).</p>
    <h3>4. Service Subscriptions</h3>
    <p>Vidhub offers several subscription plans with a range of Services for purchase, as further described in Our [Plans and Pricing Policy] [https://vidhub.co/pricing] (each, a “Service Subscription”). If You have purchased a Service Subscription, upon activation of Your account We will provide the Services under the Service Subscription that You elected. Subject to Your compliance with these Terms of Service and the other terms referenced herein, Vidhub grants You a non-exclusive, non-transferable, revocable, limited license to remotely access and use, solely for Your internal business purposes, the Vidhub software (in executable code only) (“Software”) through the Vidhub Site as permitted for the Service Subscription purchased by You.</p>
    <h3>5. Fees and Payment</h3>
    <p>You shall pay the fees set forth for the Service Subscription purchased by You in accordance with the [Plans and Pricing Policy] [https://vidhub.co/pricing]. Unless otherwise stated, all fees are quoted in U.S. Dollars. Vidhub may change its [Plans and Pricing Policy] [https://vidhub.co/pricing] and the fees for its Services from time to time in accordance with Section 15 below. Vidhub will bill You and You agree to pay for (i) the non-refundable monthly or annual fee, as applicable, in advance for the monthly or annual Service Subscription purchased by You, and (ii) the transaction fees and all other fees designated in the [Plans and Pricing Policy] [https://vidhub.co/pricing] and/or pursuant to work orders entered into by You and Vidhub, in each case in accordance with the payment terms specified in the [Plans and Pricing Policy] [https://vidhub.co/pricing] or such work order, as the case may be. Unless a different payment method is agreed in writing between You and Vidhub, Vidhub will debit all fees payable by You to Vidhub directly from the credit card account designated by You in Your account information with Us to receive the Services under the Service Subscription purchased by You and to use the Software in accordance with Section 3 above. The terms applicable to the payment method shall be between You and Your credit card company. If we suspend a portion of Your Services due to a violation by You of this Agreement or any Additional Terms, or any applicable laws or regulations, You will remain responsible for the payment of all applicable fees. All fees hereunder exclude all applicable sales, use, and other taxes and government charges, whether federal, state or foreign, and You will be responsible for payment of all such taxes (other than taxes based on Vidhub's income), fees, duties, and charges, and any related penalties and interest, arising from the payment thereof hereunder or from Your access to or receipt of the Services or Software license hereunder. Notwithstanding early termination of any given Service Subscription, You agree that You shall be responsible for paying the fees for the entire duration of the Service Subscription You ordered. Any and all amounts paid by you towards a Service Subscription are non-refundable notwithstanding early termination of such Service Subscription.</p>
    <h3>6. Your Content</h3>
    <p>We agree that You retain ownership of all information and content You provide on Your website (“Your Content”) in connection with your use of the Services. During the period that Vidhub provides Services to You, You hereby grant to Vidhub, its affiliates and service providers a non-exclusive, irrevocable, non-sublicenseable, royalty-free, worldwide license, under all of Your applicable intellectual property rights, to use, host, store, reproduce, modify, create derivative works (such as those resulting from translations, adaptations or other changes we make so that Your Content works better with Our Services), communicate, publish, publicly perform, publicly display and distribute such Content solely for purposes of providing the Services, promoting or improving our Services, and developing new ones. This license shall continue even if You stop using the Services.</p>
    <h3>7. Disclosure.</h3>
    <p>As soon as you begin to use Our Service, You agree to add a disclosure to either Your terms of use, user agreement and/or privacy policy to inform Your end-users and customers of Vidhub's access to their Personal Information through Your website, and adding a link to Our Privacy Policy which governs Our use of all such Personal Information accessed by Vidhub through Your website or through Your use of Our Services. Such disclosure shall contain not less than the following information including the link to our Privacy Policy:</p>
    <p>
      <strong>Third Party Analytics</strong>
    We have engaged Vidhub to analyse the activities of visitors to this website, and Vidhub's authorized use of cookies and other tracking technologies enable it to have access to Personal Information of visitors to this website. Such access to and use of Personal Information by Vidhub is governed by Vidhub's Privacy Policy [https://vidhub.co/privacy]."
    </p>
    <h3>8. Representations and Warranties.</h3>
    <p>You represent and warrant with respect to Your Content that: (i) You have all the rights necessary to grant the licenses granted herein to Vidhub in and to Your Content; (ii) Your Content will not infringe or misappropriate any third party's intellectual property or proprietary rights; (iii) violate any law, statute, ordinance or regulation; (iv) be defamatory, trade libelous, unlawfully threatening or harassing, or advocating, promoting or providing assistance involving violence, significant risk of death or injury, or other unlawful activities; (v) be obscene or contain child pornography; or (vi) You will use commercially reasonable endeavors to ensure Content does not contain any viruses, Trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, surreptitiously intercept or expropriate any system, data or personal information. In addition, You represent and warrant that Your use of the Services to collect or attempt to collect personally identifiable information of any person does not violate or breach any implicit or explicit agreement between You and such person or any implicit or explicit representation or warranty made by You to such person. You further represent and warrant that You will not use the Services to collect Personal Information from anyone You know or have reason to believe is under the age of 13. You shall not sublease Your account or other access to Your account to third parties; or engage in activities that may create liability for Vidhub, or its affiliates or service providers, or expose them to undue risk. Your failure to comply with the covenants set forth in this section will amount to a breach of this Agreement and is cause for immediate suspension and/or termination by Vidhub of the Services with or without notice to You.</p>
    <h3>9. Indemnity</h3>
    <p>You agree to indemnify and hold Vidhub, its affiliates, suppliers, and service providers, and each of their respective officers, directors, agents, and employees (“Indemnified Parties”), harmless from any and all losses, costs, liabilities, damages or expenses (including attorneys' and expert witnesses' fees) incurred by any party in connection with or arising from: (a) any breach of the representations or warranties in Section 8 of this Agreement, (b) Your Content, (c) Your use of the Services, or (d) claims made by any party based on Your breach of this Agreement or the Additional Terms.</p>
    <h3>10. Feedback</h3>
    <p>
    You are invited to send Us any feedback or suggestions regarding the Site, Site Content, or Services (collectively, "Feedback")
    </p>
    <h3>11. Third Party Links.</h3>
    <p>The Site may contain links to other websites operated by third parties. Such third party websites are not under the control of Vidhub and Vidhub is not responsible for the content of any third party website or any link contained in a third party website. Vidhub provides these links only as a convenience and does not review, approve, monitor, endorse, warrant, or make any representations with respect to third party websites. If You decide to access any of the third party websites linked to the Site, You do this entirely at Your own risk. Third party websites are subject to their own terms and policies, including privacy and data gathering practices. VIDHUB MAKES NO WARRANTY, EXPRESS OR IMPLIED, AS TO ANY THIRD PARTY WEBSITE LINKED TO THE SITE INCLUDING ANY WARRANTIES OF THE ACCURACY, OWNERSHIP, VALIDITY, OR LEGALITY OR ANY CONTENT OF A LINKED THIRD PARTY SITE.</p>
    <h3>12. Warranty Disclaimer.</h3>
    <p>VIDHUB IS PROVIDING THE SITE, SITE CONTENT AND SERVICES ON AN “AS IS” BASIS FOR USE AT YOUR OWN RISK. VIDHUB DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS IMPLIED, OR STATUTORY, INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OF TITLE, NONINFRINGEMENT OF THIRD PARTY RIGHTS, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, AND QUIET ENJOYMENT. VIDHUB DOES NOT WARRANT THAT ANY SITE CONTENT IS ACCURATE, COMPLETE, CURRENT, OR ERROR FREE. VIDHUB DOES NOT WARRANT THAT USE OF THE SITE, SITE CONTENT, OR SERVICES WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE, OR THAT DEFECTS WILL BE CORRECTED. Some jurisdictions do not allow the disclaimer of implied warranties, so the foregoing disclaimer may not apply to You.</p>
    <h3>13. Limitation of Liability</h3>
    <p>IN NO EVENT SHALL VIDHUB BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN CONNECTION WITH THE SITE, SITE CONTENT, OR SERVICES, INCLUDING, WITHOUT LIMITATION, ANY DAMAGES RESULTING FROM LOST USE, LOST DATA, OR LOST PROFITS, WHETHER OR NOT VIDHUB HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, ON ANY THEORY OF LIABILITY. IN NO EVENT SHALL VIDHUB TOTAL CUMULATIVE LIABILITY IN CONNECTION WITH THIS AGREEMENT (INCLUDING ANY ADDITIONAL TERMS), THE SITE, SITE CONTENT, OR SERVICES, WHETHER IN CONTRACT, TORT, OR OTHERWISE, EXCEED FIFTY DOLLARS ($50), OR IF YOU HAVE PURCHASED SERVICES FROM VIDHUB, THE SUBSCRIPTION FEE PAID BY YOU FOR SUCH SERVICES LIMITED TO THE THREE (3) MONTH PERIOD IMMEDIATELY PRECEDING THE DATE THE FIRST CLAIM GIVING RISE TO SUCH LIABILITY AROSE. THE EXISTENCE OF MORE THAN ONE CLAIM WILL NOT ALTER THE LIMITATIONS OF LIABILITY SET FORTH IN THIS SECTION. Some jurisdictions do not allow the limitation of liability, so the foregoing limitation may not apply to You.</p>
    <h3>14. Suspension and Termination</h3>
    <p>
    (a) Suspension
    </p>
    <p>
    (b) Termination
    </p>
    <p>
    (c) Rights upon Termination
    </p>
    <h3>15. Changes to Terms.</h3>
    <p>This Agreement, including any Additional Terms, are subject to occasional revision, and if We make any substantial changes, We will notify You by sending You an e-mail to the last e-mail address You provided (if Vidhub has such e-mail address in its records) or by posting notice of the changes on the Site. Any changes to this Agreement, including any Additional Terms, will be effective upon the earlier of thirty (30) calendar days following Vidhub's dispatch of an e-mail notice to You or thirty (30) calendar days following Vidhub's posting of notice of the changes on the Site. These changes will be effective immediately for new users of the Site, Site Content, or Services. Continued use of the Site, Site Content, or Services following notice of such changes shall indicate Your acknowledgement of such changes and agreement to be bound by the terms and conditions of such changes. If You object to any change, Your sole recourse shall be to immediately terminate Your account and cease using the Site, Site Content, and Services. You should periodically visit this page and the pages at the URL referenced in Section 1 above relating to the Additional Terms to examine the then current Agreement and Additional Terms.</p>
    <h3>16. Modificiation.</h3>
    <p>Vidhub reserves the right, at any time, to modify the Site, Site Content, or any part thereof or Services, or to modify, suspend, or discontinue the Site, Site Content, or Services, or any part thereof with or without notice. You agree that Vidhub will not be liable to You or to any third party for any modification, suspension, or discontinuance of the Site, Site Content, or Services, or any part thereof.</p>
    <h3>17. Force Majeure.</h3>
    <p>Except for the payment of any fees due and payable under this Agreement, neither party's delay in the performance of any duties or obligations under this Agreement will be considered a breach of this Agreement if such delay is caused by any labor dispute, shortage of materials, fire, earthquake, flood, telecommunications failure, failure of Vidhub's cloud service provider, or any other cause beyond a party’s reasonable control.</p>
    <h3>18. General Provisions.</h3>
    <p>You and Vidhub are independent contractors, and no agency, partnership, joint venture, employee-employer or franchiser-franchisee relationship is intended or created by this Agreement. You shall not assign, transfer or delegate this Agreement or any rights or obligations hereunder. Any assignment, transfer or delegation in contravention of the foregoing provision shall be null and void. You agree that this Agreement may be assigned by Vidhub, in Vidhub's sole discretion. If any provision of this Agreement is, for any reason, held to be invalid or unenforceable, the other provisions of this Agreement will be unimpaired and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law. This Agreement and any action related thereto will be governed, controlled, interpreted, and defined by and under the laws of the State of California, without giving effect to any conflicts of laws principles that require the application of the law of a different state or jurisdiction. By using the Site, Site Content or Services, You hereby expressly consent to the personal jurisdiction and venue in the state and federal courts for Santa Clara County, California for any lawsuit filed there against You by Vidhub arising from or related to this Agreement. This Agreement (which includes the Additional Terms) constitutes the entire agreement between You and Vidhub regarding the use of the Site, Site Content, and Services.</p>
    <h3>19. Questions.</h3>
    <p>If You have any questions about this Agreement or any Additional Terms, please contact Us by e-mail at terms@vidhub.co, marking the message "Attention: Terms."</p>
  </Page>
);

export default PrivacyPage;
